version: '3'
services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    container_name: postgres_db_amex
    networks:
      - nextdoor

networks:
  nextdoor:
    driver: bridge
